### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by grlndgz** [Roundaround/mc-fabric-sprint-indicator#2]
The game crashes as soon as I try to sprint. I've got several of your other mods installed and they all seem to work fine.

[crash-2023-03-11_09.54.45-client.txt](https://github.com/Roundaround/mc-fabric-sprint-indicator/files/10949118/crash-2023-03-11_09.54.45-client.txt)

(This is Black Market Beagle from Link's stream btw.)

**Comment by Roundaround** [comment]
Thank you for reporting! I don't know exactly what's going on, because sometimes it works and sometimes it doesn't. My best guess is some kind of mod incompatibility. Either way, I've updated/compiled a proper 1.19.3 version, so hopefully that one works better for you!

https://modrinth.com/mod/roundaround-sprint-indicator/version/1.0.1+1.19.3

**Comment by grlndgz** [comment]
That did it. Thanks for the super-fast turn-around!!
